In [1]:
import pandas as pd

In [2]:
def add_id_to_df(df):
    df['ID'] = df['batch'].astype(str) + '/' + df['cell_line'].astype(str) + '/' + df['panel'].astype(str) + '/' +  df['condition'].astype(str) + '/' +  df['rep'].astype(str) + '/' + df['marker'].astype(str) + '/' + df['filename'].astype(str)
    return df

In [3]:
df_old = pd.read_csv("/home/projects/hornsteinlab/Collaboration/MOmaps/outputs/preprocessing/spd/logs/preprocessing_FUS/batch1/original_all_good_but_specfici_markers/cell_count_stats_230224_112751_143123.csv")
df_old = add_id_to_df(df_old)
df_old

,DATETIME,filename,batch,cell_line,panel,condition,rep,marker,cells_counts,valid_tiles_indexes,...,whole_cells_counts,whole_cells_count_mean,whole_cells_count_std,n_valid_tiles,site_cell_count,cells_count_in_valid_tiles_mean,cells_count_in_valid_tiles_std,whole_cells_count_in_valid_tiles_mean,whole_cells_count_in_valid_tiles_std,ID
0,230224_112826,Panel_D1_w1confDAPI_s322,batch1,FUSHeterozygous,panelD,MG132,rep1,DAPI,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[],...,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.00,0.00,0,0.0,NaN,NaN,NaN,NaN,batch1/FUSHeterozygous/panelD/MG132/rep1/DAPI/...
1,230224_112826,MME_Panel_A1_w1confDAPI_s394,batch1,FUSHeterozygous,panelA,MG132,rep1,DAPI,[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[5],...,[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.02,0.12,1,4.0,1.0,0.0,1.0,0.0,batch1/FUSHeterozygous/panelA/MG132/rep1/DAPI/...
2,230224_112826,MME_Panel_C1_w1confDAPI_s396,batch1,FUSHeterozygous,panelC,MG132,rep1,DAPI,[0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0...,[17 59],...,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0...,0.03,0.17,2,9.0,1.0,0.0,1.0,0.0,batch1/FUSHeterozygous/panelC/MG132/rep1/DAPI/...
3,230224_112826,MME_Panel_B1_w4confCy5_s342,batch1,FUSHeterozygous,panelB,MG132,rep1,DAPI,[1 1 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0...,[ 1 14 32 47 59],...,[0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0...,0.08,0.27,5,8.0,1.2,0.4,1.0,0.0,batch1/FUSHeterozygous/panelB/MG132/rep1/DAPI/...
4,230224_112827,MME_Panel_B1_w4confCy5_s342,batch1,FUSHeterozygous,panelB,MG132,rep1,TDP43,NaN,[ 1 14 32 47 59],...,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,batch1/FUSHeterozygous/panelB/MG132/rep1/TDP43...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176069,240224_054224,CCN_Panel_J1_w3confmCherry_s115,batch1,KOLF,panelJ,Colchicine,rep2,PML,NaN,[ 1 2 5 12 25 29 30 43 52 57],...,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelJ/Colchicine/rep2/PML/CCN_Pan...
176070,240224_054225,CCN_Panel_J1_w3confmCherry_s109,batch1,KOLF,panelJ,Colchicine,rep2,PML,NaN,[ 5 8 15 18 34 54 58],...,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelJ/Colchicine/rep2/PML/CCN_Pan...
176071,240224_054229,CCN_Panel_J1_w3confmCherry_s200,batch1,KOLF,panelJ,Colchicine,rep2,PML,NaN,[16 18 29 30 35 39 50 51 62],...,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelJ/Colchicine/rep2/PML/CCN_Pan...
176072,240224_054231,CCN_Panel_J1_w3confmCherry_s184,batch1,KOLF,panelJ,Colchicine,rep2,PML,NaN,[21 28 42 50 52 59 60],...,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelJ/Colchicine/rep2/PML/CCN_Pan...
176073,240224_054233,CCN_Panel_J1_w3confmCherry_s190,batch1,KOLF,panelJ,Colchicine,rep2,PML,NaN,[ 0 13 21 22 44 47],...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelJ/Colchicine/rep2/PML/CCN_Pan...

In [4]:
df_new = pd.read_csv("/home/projects/hornsteinlab/Collaboration/MOmaps/outputs/preprocessing/spd/logs/preprocessing_FUS/batch1/cell_count_stats_260224_202119_247477.csv")#cell_count_stats_250224_172417_280703.csv")
df_new = df_new[df_new['marker']!='DAPI'] # Drop DAPI otherwise there are duplicates since DAPI can come from different filenames
df_new = add_id_to_df(df_new)
df_new

,DATETIME,filename,batch,cell_line,panel,condition,rep,marker,cells_counts,valid_tiles_indexes,...,whole_cells_counts,whole_cells_count_mean,whole_cells_count_std,n_valid_tiles,site_cell_count,cells_count_in_valid_tiles_mean,cells_count_in_valid_tiles_std,whole_cells_count_in_valid_tiles_mean,whole_cells_count_in_valid_tiles_std,ID
3,260224_202147,MME_Panel_B1_w4confCy5_s342,batch1,FUSHeterozygous,panelB,MG132,rep1,TDP43,NaN,[ 1 14 32 47 59],...,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,batch1/FUSHeterozygous/panelB/MG132/rep1/TDP43...
4,260224_202147,MME_Panel_C1_w4confCy5_s393,batch1,FUSHeterozygous,panelC,MG132,rep1,FMRP,NaN,[47],...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,batch1/FUSHeterozygous/panelC/MG132/rep1/FMRP/...
6,260224_202149,Panel_D1_w2confGFP_s369,batch1,FUSHeterozygous,panelD,MG132,rep1,PSD95,NaN,[57],...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,batch1/FUSHeterozygous/panelD/MG132/rep1/PSD95...
9,260224_202149,MME_Panel_C1_w4confCy5_s360,batch1,FUSHeterozygous,panelC,MG132,rep1,FMRP,NaN,[ 2 15 24 47 58],...,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,batch1/FUSHeterozygous/panelC/MG132/rep1/FMRP/...
10,260224_202149,MME_Panel_B1_w4confCy5_s349,batch1,FUSHeterozygous,panelB,MG132,rep1,TDP43,NaN,[ 2 10 13 20],...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,batch1/FUSHeterozygous/panelB/MG132/rep1/TDP43...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76419,270224_044640,CCN_Panel_E1_w3confCy5_s200,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[23 34 48 50 54 55 62],...,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelE/Colchicine/rep2/DCP1A/CCN_P...
76420,270224_044640,CCN_Panel_E1_w3confCy5_s156,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[ 1 24 39],...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelE/Colchicine/rep2/DCP1A/CCN_P...
76421,270224_044640,CCN_Panel_E1_w3confCy5_s122,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[25 57 60],...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelE/Colchicine/rep2/DCP1A/CCN_P...
76422,270224_044640,CCN_Panel_E1_w3confCy5_s118,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[44 48 53 56],...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelE/Colchicine/rep2/DCP1A/CCN_P...
76423,270224_044640,CCN_Panel_E1_w3confCy5_s146,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[ 7 41],...,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,batch1/KOLF/panelE/Colchicine/rep2/DCP1A/CCN_P...

In [5]:
df_final = df_old.copy()
# drop old values
df_final = df_old[~df_old['ID'].isin(df_new['ID'])]
# append new ones
df_final = pd.concat([df_final, df_new], ignore_index=True)
df_final.drop(columns=['ID'], inplace=True)
df_final

,DATETIME,filename,batch,cell_line,panel,condition,rep,marker,cells_counts,valid_tiles_indexes,...,cells_count_std,whole_cells_counts,whole_cells_count_mean,whole_cells_count_std,n_valid_tiles,site_cell_count,cells_count_in_valid_tiles_mean,cells_count_in_valid_tiles_std,whole_cells_count_in_valid_tiles_mean,whole_cells_count_in_valid_tiles_std
0,230224_112826,Panel_D1_w1confDAPI_s322,batch1,FUSHeterozygous,panelD,MG132,rep1,DAPI,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[],...,0.00,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.00,0.00,0,0.0,NaN,NaN,NaN,NaN
1,230224_112826,MME_Panel_A1_w1confDAPI_s394,batch1,FUSHeterozygous,panelA,MG132,rep1,DAPI,[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[5],...,0.31,[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.02,0.12,1,4.0,1.0,0.0,1.0,0.0
2,230224_112826,MME_Panel_C1_w1confDAPI_s396,batch1,FUSHeterozygous,panelC,MG132,rep1,DAPI,[0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0...,[17 59],...,0.49,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0...,0.03,0.17,2,9.0,1.0,0.0,1.0,0.0
3,230224_112826,MME_Panel_B1_w4confCy5_s342,batch1,FUSHeterozygous,panelB,MG132,rep1,DAPI,[1 1 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0...,[ 1 14 32 47 59],...,0.44,[0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0...,0.08,0.27,5,8.0,1.2,0.4,1.0,0.0
4,230224_112829,Panel_D1_w1confDAPI_s355,batch1,FUSHeterozygous,panelD,MG132,rep1,DAPI,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[],...,0.00,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.00,0.00,0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182495,270224_044640,CCN_Panel_E1_w3confCy5_s200,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[23 34 48 50 54 55 62],...,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN
182496,270224_044640,CCN_Panel_E1_w3confCy5_s156,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[ 1 24 39],...,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
182497,270224_044640,CCN_Panel_E1_w3confCy5_s122,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[25 57 60],...,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
182498,270224_044640,CCN_Panel_E1_w3confCy5_s118,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[44 48 53 56],...,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN
182499,270224_044640,CCN_Panel_E1_w3confCy5_s146,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[ 7 41],...,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN

In [6]:
# Save final to file
df_final.to_csv("/home/projects/hornsteinlab/Collaboration/MOmaps/outputs/preprocessing/spd/logs/preprocessing_FUS/merged/batch1/cell_count_stats_270224.csv", index=False)

In [7]:
# test
k = pd.read_csv("/home/projects/hornsteinlab/Collaboration/MOmaps/outputs/preprocessing/spd/logs/preprocessing_FUS/merged/batch1/cell_count_stats_270224.csv")
k

/tmp/ipykernel_80042/2368229783.py:2: DtypeWarning: Columns (8,12) have mixed types. Specify dtype option on import or set low_memory=False.
  k = pd.read_csv("/home/labs/hornsteinlab/Collaboration/MOmaps/outputs/preprocessing/spd/logs/preprocessing_FUS/merged/batch1/cell_count_stats_270224.csv")

,DATETIME,filename,batch,cell_line,panel,condition,rep,marker,cells_counts,valid_tiles_indexes,...,cells_count_std,whole_cells_counts,whole_cells_count_mean,whole_cells_count_std,n_valid_tiles,site_cell_count,cells_count_in_valid_tiles_mean,cells_count_in_valid_tiles_std,whole_cells_count_in_valid_tiles_mean,whole_cells_count_in_valid_tiles_std
0,230224_112826,Panel_D1_w1confDAPI_s322,batch1,FUSHeterozygous,panelD,MG132,rep1,DAPI,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[],...,0.00,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.00,0.00,0,0.0,NaN,NaN,NaN,NaN
1,230224_112826,MME_Panel_A1_w1confDAPI_s394,batch1,FUSHeterozygous,panelA,MG132,rep1,DAPI,[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[5],...,0.31,[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.02,0.12,1,4.0,1.0,0.0,1.0,0.0
2,230224_112826,MME_Panel_C1_w1confDAPI_s396,batch1,FUSHeterozygous,panelC,MG132,rep1,DAPI,[0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0...,[17 59],...,0.49,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0...,0.03,0.17,2,9.0,1.0,0.0,1.0,0.0
3,230224_112826,MME_Panel_B1_w4confCy5_s342,batch1,FUSHeterozygous,panelB,MG132,rep1,DAPI,[1 1 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0...,[ 1 14 32 47 59],...,0.44,[0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0...,0.08,0.27,5,8.0,1.2,0.4,1.0,0.0
4,230224_112829,Panel_D1_w1confDAPI_s355,batch1,FUSHeterozygous,panelD,MG132,rep1,DAPI,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,[],...,0.00,[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...,0.00,0.00,0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182495,270224_044640,CCN_Panel_E1_w3confCy5_s200,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[23 34 48 50 54 55 62],...,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN
182496,270224_044640,CCN_Panel_E1_w3confCy5_s156,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[ 1 24 39],...,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
182497,270224_044640,CCN_Panel_E1_w3confCy5_s122,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[25 57 60],...,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
182498,270224_044640,CCN_Panel_E1_w3confCy5_s118,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[44 48 53 56],...,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN
182499,270224_044640,CCN_Panel_E1_w3confCy5_s146,batch1,KOLF,panelE,Colchicine,rep2,DCP1A,NaN,[ 7 41],...,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Check all unique
k = add_id_to_df(k)
k['ID'].value_counts()